"""empty message

Revision ID: dd365a8a80ea
Revises: bc48d2a558da
Create Date: 2023-01-15 23:28:41.266565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd365a8a80ea'
down_revision = 'bc48d2a558da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'title')
    # ### end Alembic commands ###