"""empty message

Revision ID: 986db527a3b8
Revises: dd365a8a80ea
Create Date: 2023-01-17 14:20:11.327129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986db527a3b8'
down_revision = 'dd365a8a80ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('about_me', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('website_url', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('twitter_url', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('github_url', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_url')
    op.drop_column('users', 'twitter_url')
    op.drop_column('users', 'website_url')
    op.drop_column('users', 'about_me')
    op.drop_column('users', 'title')
    op.drop_column('users', 'location')

    # ### end Alembic commands ###